services:
  es:
    ports:
      - 9200:9200
    image: 'docker.elastic.co/elasticsearch/elasticsearch:7.6.1'
    environment:
      discovery.type: single-node
    networks:
      - storage
    volumes:
      - ./temp/esdata:/usr/share/elasticsearch/data

  postgres:
    ports:
      - 5432:5432
    image: 'postgres:13'
    environment:
      POSTGRES_USER: compass
      POSTGRES_PASSWORD: compass_password
      POSTGRES_DB: compass
    networks:
      - storage
    volumes:
      - ./temp/pgdata:/var/lib/postgresql/data

networks:
  storage: