services:
  es:
    ports:
      - 9200:9200
    image: 'elasticsearch:7.6.1'
    environment:
      discovery.type: single-node
  postgres:
    ports:
      - 5432:5432
    image: 'postgres:13'
    environment:
      POSTGRES_USER: columbus
      POSTGRES_PASSWORD: columbus_password
      POSTGRES_DB: columbus
      discovery.type: single-node
