name: Build
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Get release tag
      id: get_version
      uses: battila7/get-version-action@v2
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        file: "./Dockerfile.dev"
        tags: |
            odpf/columbus:latest
            odpf/columbus:${{ steps.get_version.outputs.version-without-v }}
