name: Test
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      elasticsearch:
        image: elasticsearch:7.17.9
        ports:
          - 9200:9200
        env:
          ES_TEST_SERVER_URL: "http://elasticsearch:9200"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: "1.20"
      - name: Install dependencies
        run: sudo apt-get install build-essential
      - name: Install packages
        run: go mod tidy
      - name: Run Test
        run: make test
      - name: Install goveralls and send coverage
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          go install github.com/mattn/goveralls@latest
          goveralls -coverprofile=coverage.txt -service=github
